# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app
  pod 'GoogleSignIn'

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNLanguages', :path => '../node_modules/react-native-languages'

    pod 'RNI18n', :path => '../node_modules/react-native-i18n'

    pod 'react-native-locale', :path => '../node_modules/react-native-locale'

    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

  end

  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app-tvOS

end
